baseurl = "https://austinjadams.com/blog/"
languageCode = "en-us"
title = "austin's lousy blog"
# toolbag/nginx handle 404s for us
disable404 = true
disableRSS = true
disableSitemap = false

[params]
homeurl = "/"
description = "austin adams's terrible, horrible, no good, very bad blog"
