baseurl = "https://austinjadams.com/"
languageCode = "en-us"
title = "austin j. adams"
# toolbag/nginx handle 404s for us
disable404 = true
disableRSS = true
disableSitemap = true

[params]
homeurl = "/"
tagline = "computer science PhD student"
description = "Austin Adams's personal website and blog"
# The title in the <title> tag
titletitle = "Austin Adams"
email = "aja@gatech.edu"

[markup.goldmark.renderer]
unsafe=true
